export const COHORT_PASSWORD = "MSM@2027";

export const COHORT_STUDENTS = [
  { name: "Aditya Jain", rollNumber: "25M101" },
  { name: "Aditya Rajoriya", rollNumber: "25M102" },
  { name: "Akarsh Bajpai", rollNumber: "25M103" },
  { name: "Akash Degala", rollNumber: "25M104" },
  { name: "Amisha Dash", rollNumber: "25M105" },
  { name: "Anindya Srivastava", rollNumber: "25M106" },
  { name: "Arohi Khurana", rollNumber: "25M107" },
  { name: "Astha Chitransh", rollNumber: "25M108" },
  { name: "Ayush Kumar", rollNumber: "25M109" },
  { name: "Bhagirath Kaushal", rollNumber: "25M110" },
  { name: "Dhruvil Agrawal", rollNumber: "25M112" },
  { name: "Divyanshu Batra", rollNumber: "25M113" },
  { name: "Ena De", rollNumber: "25M114" },
  { name: "Girisha Gupta", rollNumber: "25M115" },
  { name: "Gurasees Chadha", rollNumber: "25M116" },
  { name: "Kashish Bhutada", rollNumber: "25M117" },
  { name: "Kavery Parasher", rollNumber: "25M118" },
  { name: "Khushi Mishra", rollNumber: "25M120" },
  { name: "Komal Kashyap", rollNumber: "25M121" },
  { name: "Krishang Dewan", rollNumber: "25M122" },
  { name: "Kumbhar Soham Prabhakar", rollNumber: "25M123" },
  { name: "Mihika Nair", rollNumber: "25M125" },
  { name: "Naman Upadhyaya", rollNumber: "25M127" },
  { name: "Navneet Kumar C", rollNumber: "25M128" },
  { name: "Niharika Nayan Jha", rollNumber: "25M129" },
  { name: "Pranathi S Shah", rollNumber: "25M130" },
  { name: "Pranav Arora", rollNumber: "25M131" },
  { name: "Pranshu Sharma", rollNumber: "25M132" },
  { name: "Pratyush Kumar", rollNumber: "25M133" },
  { name: "Prerna Das", rollNumber: "25M134" },
  { name: "Raghav Sukhija", rollNumber: "25M135" },
  { name: "Ram J Pareek", rollNumber: "25M136", role: "ADMIN" as const },
  { name: "Ravjot Singh Bagga", rollNumber: "25M137" },
  { name: "Reshikesh C", rollNumber: "25M138" },
  { name: "Ritika Jain", rollNumber: "25M139" },
  { name: "Ritika Laddha", rollNumber: "25M140" },
  { name: "Riya George", rollNumber: "25M141" },
  { name: "Ronit Singh", rollNumber: "25M142" },
  { name: "Samyak Khatri", rollNumber: "25M143" },
  { name: "Sanidhya", rollNumber: "25M144" },
  { name: "Saumya", rollNumber: "25M145" },
  { name: "Sharanjit Pakrasi", rollNumber: "25M146" },
  { name: "Sneha Kumari", rollNumber: "25M147" },
  { name: "Srijita Saha", rollNumber: "25M148" },
  { name: "Tipparaju Venkata Sai Bhavyasri", rollNumber: "25M149" },
  { name: "Unnikrishnan R Menon", rollNumber: "25M150" },
  { name: "Vadlamudi Venkata Sri Harsha", rollNumber: "25M151" },
  { name: "Vaishnavi B Kudachimath", rollNumber: "25M152" },
  { name: "Vanshika Goel", rollNumber: "25M153" },
  { name: "Yaushnika Singh", rollNumber: "25M154" },
  { name: "Anirudh Sharma", rollNumber: "25M156" },
  { name: "Nimai Krishna", rollNumber: "25M157" },
  { name: "Akanksha Anil Magar", rollNumber: "25M158" },
  { name: "Tanmay Singh", rollNumber: "25M159" },
  { name: "Kartik N Pai", rollNumber: "25M160" },
  { name: "Gautham Kaushik", rollNumber: "25M161" },
  { name: "Siddhant Tonpe", rollNumber: "25M162" },
  { name: "Harshit Girish Mathkar", rollNumber: "25M163" },
  { name: "Ayuj Saha", rollNumber: "25M164" },
];
